server:
  port: ${SERVER_PORT:8060}

spring:
  mongodb:
    uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_SERVICE_PORT}/auth?authSource=admin
  rabbitmq:
    host: ${RABBIT_HOST}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    port: 5672

    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000ms

queues:
  user-creation:
    name: user.creation

jwt:
  public-key: ${JWT_PUBLIC_KEY}
  public-key-expiration: ${JWT_PUBLIC_KEY_EXPIRATION}
  private-key: ${JWT_PRIVATE_KEY}
  private-key-expiration: ${JWT_PRIVATE_KEY_EXPIRATION}

oauth:
  yandex:
    id: ${OAUTH_YANDEX_ID}
    secret: ${OAUTH_YANDEX_SECRET}
